/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.teketaximaven;

import java.awt.Dialog;
import java.awt.EventQueue;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.sql.*;
import javax.swing.*;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author Riverbank
 */
public class Welcome extends javax.swing.JFrame {

    private Object javaconnect;
    private Object JOptionpane;
    private Object conn;
    // The username for the logged in user
    private String username;
    private Object userslist;
    private int id;

    public Welcome(String username) {
        this.username = username;
        Booking_info();
    }

    public void Booking_info() {
        initComponents();
        //conn= javaconnect.DbConnect();
        updateTable();

    }

    public void updateTable() {

//        if( username .getSource().equals() ){
        try {

            DbConnect dbConn = new DbConnect();
            Connection connection = dbConn.getConnection();

            String sql = "select* from reservation r left join users u on r.users_id = u.id where u.username=? ";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, username);

            //  pst = conn.PreparedStatement(sql);
            ResultSet rs = pst.executeQuery();
            //  reservation_table.setModel (DbUtils.resultSetToTableModel(rs));
            DefaultTableModel model = (DefaultTableModel) reservation_table.getModel();
            model.getDataVector().clear();
            while (rs.next()) {

                model.addRow(new Object[]{ rs.getString("pick_up"), rs.getString("destination"),rs.getString("description"), rs.getString("vehicle_class"), rs.getString("capacity"), rs.getString("purpose"), rs.getString("chargestructure"),  rs.getString("DateandTime")});
                // reservation_table.getModel().

            }
            ((DefaultTableModel) reservation_table.getModel()).fireTableDataChanged();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);

        }
//        }
    }

    /**
     * Creates new form Welcome
     */
    public void clock() {

        Thread clock = new Thread() {
            public void run() {
                try {
                    for (;;) {
                        Calendar cal = new GregorianCalendar();
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        int month = cal.get(Calendar.MONTH);
                        int year = cal.get(Calendar.YEAR);
                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);
                        lblTime.setText(" Date " + year + "-" + month + "-" + day + " Time " + hour + ":" + minute
                                + ":" + second);

                        sleep(1000);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        clock.start();
    }

    public Welcome(String id, String pick_up, String destination, String vehicle_class, String capacity, String purpose, String chargestructure, String description, String dateandTime) {
        initComponents();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        BookingDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        Combostructure = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combocapacity = new javax.swing.JComboBox();
        Comboclass = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfrom = new javax.swing.JTextField();
        txtto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtinstruction = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpurpose = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null,Calendar.MINUTE);
        time = new javax.swing.JSpinner(sm);
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservation_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        jLabel2.setText("Charge Structure");

        Combostructure.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "open ", "Aaiport", "fixed", " ", " " }));
        Combostructure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombostructureActionPerformed(evt);
            }
        });

        jLabel3.setText("Vehicle Capacity");

        jLabel4.setText("Vehicle Class");

        combocapacity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4 pax", "7 pax" }));

        Comboclass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic", "Luxury" }));
        Comboclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboclassActionPerformed(evt);
            }
        });

        jLabel5.setText("From");

        jLabel6.setText("To");

        txtto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttoActionPerformed(evt);
            }
        });

        jLabel7.setText("Description/Instructions");

        txtinstruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinstructionActionPerformed(evt);
            }
        });

        jLabel8.setText("Purpose");

        txtpurpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpurposeActionPerformed(evt);
            }
        });

        jLabel9.setText("Date and Time");

        //JSpinner time = new JSpinner(sm);

        JSpinner.DateEditor de = new JSpinner.DateEditor(time, "dd-MMM-yyyy hh:mm a");

        time.setEditor(de);
        System.out.println("Spinner:      "+de.getFormat().format(time.getValue()));

        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookingDialogLayout = new javax.swing.GroupLayout(BookingDialog.getContentPane());
        BookingDialog.getContentPane().setLayout(BookingDialogLayout);
        BookingDialogLayout.setHorizontalGroup(
            BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingDialogLayout.createSequentialGroup()
                .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combostructure, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BookingDialogLayout.createSequentialGroup()
                                .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(txtfrom))
                                .addGap(42, 42, 42)
                                .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(txtto)))
                            .addGroup(BookingDialogLayout.createSequentialGroup()
                                .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combocapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)
                                .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Comboclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BookingDialogLayout.createSequentialGroup()
                                .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtinstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpurpose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(BookingDialogLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton5)
                        .addGap(96, 96, 96)
                        .addComponent(jButton6)))
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(353, 353, 353))
        );
        BookingDialogLayout.setVerticalGroup(
            BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingDialogLayout.createSequentialGroup()
                .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingDialogLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Combostructure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Comboclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combocapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(BookingDialogLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingDialogLayout.createSequentialGroup()
                        .addComponent(txtinstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addGroup(BookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addComponent(txtpurpose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(168, 240, 240));

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Book Now");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblTime.setText("Clock");
        lblTime.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblTimeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        reservation_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "pick_up", "Destination", "description", "Vehicle_class", "capacity", "purpose ", "chargestructure", "Date and Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        reservation_table.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                reservation_tableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(reservation_table);

        jLabel1.setText("BOOK CABS ONLINE ANYTIME ANYWHERE IN KENYA");

        jButton3.setText("Delete reservation");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton2)
                .addGap(52, 52, 52)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 567, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login y = new Login();
                y.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        open();
//        Booking s = new Booking();
        BookingDialog.pack();
        BookingDialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        BookingDialog.setVisible(true);
        updateTable();

        BookingDialog.update(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblTimeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblTimeAncestorAdded
        // TODO add your handling code here:
        clock();
    }//GEN-LAST:event_lblTimeAncestorAdded

    private void reservation_tableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_reservation_tableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_reservation_tableAncestorAdded

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DbConnect dbConn = new DbConnect();
        Connection connection = dbConn.getConnection();
        int row = reservation_table.getSelectedRow();
        // String cell = reservation_table.getModel().getValueAt(row,0).toString();
        String sql = "delete from reservation where id= ?";

        if (row >= 0) {
            try {
                PreparedStatement pst = connection.prepareStatement(sql);
                pst.setString(1, (String) ((DefaultTableModel) reservation_table.getModel()).getValueAt(row, 0));
                pst.execute();
                JOptionPane.showMessageDialog(null, "deleted successfully");
                updateTable();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e);
                // return (E) elementData[index];

            }
        } else {
            JOptionPane.showMessageDialog(null, "select the reservation to be deleted");

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CombostructureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombostructureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CombostructureActionPerformed

    private void ComboclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboclassActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboclassActionPerformed

    private void txttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttoActionPerformed

    private void txtinstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinstructionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinstructionActionPerformed

    private void txtpurposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpurposeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpurposeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {

            DbConnect dbConn = new DbConnect();
            Connection connection = dbConn.getConnection();
            String query1 = "select id from users  where username =?";

            PreparedStatement pst2 = connection.prepareStatement(query1);
            pst2.setString(1, username);
//            pst2.executeUpdate();
            ResultSet executeQuery = pst2.executeQuery();
            executeQuery.next();
            int users_id = executeQuery.getInt(1);

            String query = " insert ignore into reservation (pick_up,destination,description,vehicle_class,capacity,purpose,chargeStructure,DateandTime,users_id)"
                    + " values (?, ?, ?, ?, ?, ?, ?,?,?)";
            PreparedStatement pst = connection.prepareStatement(query);
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy hh:mm a");

            Date parse = (Date) time.getValue();

            SimpleDateFormat sdfDb = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

            String format = sdfDb.format(parse);

            pst.setString(1, txtfrom.getText());
            pst.setString(2, txtto.getText());
            pst.setString(3, txtinstruction.getText());
            pst.setString(4, (String) Comboclass.getSelectedItem());
            pst.setString(5, (String) combocapacity.getSelectedItem());
            pst.setString(6, txtpurpose.getText());
            pst.setString(7, (String) Combostructure.getSelectedItem());
            pst.setString(8, format);
            pst.setInt(9, users_id);
            // time = new javax.swing.JSpinner(sm);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Successfully saved");
        } catch (Exception ex) {
            ex.printStackTrace();

            JOptionPane.showMessageDialog(null, ex);

        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here
        BookingDialog.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed
    private void open() {
        // TODO Auto-generated method stub
        //Frame.getFrames();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome("id", "pick_up", "destination", "vehicle_class", "capacity", "purpose", "chargestructure", "description", "DateandTime").setVisible(true);
            }
        });
    }

    protected void close() {
        // TODO Auto-generated method stub
        //this.dispatchEvent(this, WindowEvent.WINDOW_CLOSING));

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog BookingDialog;
    private javax.swing.JComboBox Comboclass;
    private javax.swing.JComboBox Combostructure;
    private javax.swing.JComboBox combocapacity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTable reservation_table;
    private javax.swing.JSpinner time;
    private javax.swing.JTextField txtfrom;
    private javax.swing.JTextField txtinstruction;
    private javax.swing.JTextField txtpurpose;
    private javax.swing.JTextField txtto;
    // End of variables declaration//GEN-END:variables

}
